---
name: Build Debian Packages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build deb
        uses: DominicOrsi/cargo-deb-ubuntu@1.0.0
        # uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0 -- does not work
        # uses: novalabsxyz/cargo-deb-amd64-ubuntu@v2.7
        # uses: catango/build-rust-deb-action@0.9
        # uses: sassman/rust-deb-builder@v1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: w6otx
          path: "*.deb"

      - name: Upload release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "*.deb"
