---
name: Build Debian Packages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build deb
        uses: DominicOrsi/cargo-deb-ubuntu@1.0.0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: w6otx
          path: "*.deb"

      - name: Upload release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "*.deb"
